# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cnBtze3vQsdROgZbMmulItgUbMu7vVgb
"""

#python MCQ
#1: b)
#2: b)
#3: c)
#4: a)
#5: a)

#python practical
#2
def reverse_string(s):
    return s[::-1]

input_string = "hello"
reversed_string=  reverse_string(input_string)
print("Original:", input_string)
print("Reversed:", reversed_string)

#5
def factorial(n):
    if n < 0:
        return "Factorial is not defined for negative numbers"
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

number = int(input("enter any number:"))
print(f"Factorial of {number} is: {factorial(number)}")

#numpy mcq
#1: a)
#2: a)
#3: b)
#4: d)
#5: a)
#practical
#1:
import numpy as np
new_array = np.arange(2, 21, 2)
print(new_array)

#pandas
#1: a)
#2: a)
#3: a)
#4: a)
#5: a)
#practical
#1
import pandas as pd
df = pd.DataFrame({'Name': ['Alice','Bob','Charlie'],
                   'Age': [25,30,35]})
print(df)
#3
import pandas as pd
df1 = pd.DataFrame({
    'EmpID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']})

df2 = pd.DataFrame({
    'EmpID': [1, 2, 4],
    'Dept': ['HR', 'Engineering', 'Finance']})
merged_df = pd.merge(df1, df2)

print(merged_df)